name: Daily Commit Workflow

on:
  schedule:
    - cron: '40 3 * * *'  # Runs every day at 05:25 UTC
  workflow_dispatch:       # (Optional) allows manual triggering too

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Append timestamp by 24f2007947@ds.study.iitm.ac.in
        run: |
          echo "Last run: $(date -u)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily update at $(date -u)"
          git push
